description = "Ting Bill YYYY-MM-DD"

deviceIds = [ "1112223333", "1112224444", "1112220000" ]
shortStrawId = "1112220000"

total = 118.84

devices = 42.00

minutes = 35.00
messages = 8.00
megabytes = 20.00

extraMinutes = 1.00
extraMessages = 2.00
extraMegabytes = 3.00

fees = 28.74
